export interface Vendor {
  id: string;
  name: string;
  service_type?: string | null;
  contact_person?: string | null;
  email?: string | null;
  contact_number?: string | null;
  address?: string | null;
  gst_number?: string | null;
  licence_url?: string | null;
  certificate_url?: string | null;
  status?: "Active" | "Inactive" | "Pending" | "Suspended" | string;
  
  vendor_code?: string | null;
  vendor_category?: string | null;
  business_name?: string | null;
  mobile_number?: string | null;
  alternate_mobile_number?: string | null;
  website?: string | null;
  whatsapp_number?: string | null;
  address_line_1?: string | null;
  address_line_2?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  zip_code?: string | null;
  pan_number?: string | null;
  registration_number?: string | null;
  license_number?: string | null;
  trade_license_number?: string | null;
  years_of_experience?: number | null;
  available_days?: string | null;
  working_hours?: string | null;
  emergency_service?: boolean | null;
  support_24_7?: boolean | null;
  contract_start_date?: string | null;
  contract_end_date?: string | null;
  contract_value?: number | null;
  payment_terms?: string | null;
  contract_document_url?: string | null;
  renewal_reminder?: boolean | null;
  bank_account_name?: string | null;
  bank_name?: string | null;
  bank_account_number?: string | null;
  bank_ifsc_code?: string | null;
  bank_upi_id?: string | null;
  gst_certificate_url?: string | null;
  pan_card_url?: string | null;
  business_license_url?: string | null;
  insurance_certificate_url?: string | null;
  agreement_copy_url?: string | null;
  identity_proof_url?: string | null;
  address_proof_url?: string | null;
  other_documents_url?: string | null;
  vendor_rating?: number | null;
  preferred_vendor?: boolean | null;
  verified_vendor?: boolean | null;
  remarks?: string | null;
  association_name?: string | null;
  assigned_blocks?: string | null;
  assigned_services?: string | null;
  services_offered_json?: string | null;
  contact_details_json?: string | null;
  created_at?: string;
}

export type VendorCreatePayload = Omit<Vendor, "id" | "created_at">;
export type VendorUpdatePayload = Partial<VendorCreatePayload>;
