import React from "react";
import * as LucideIcons from "lucide-react";
import BadmintonIcon from "./custom/BadmintonIcon";
import SwimmingIcon from "./custom/SwimmingIcon";
import NestoraLogo from "./custom/NestoraLogo";
import { Icon } from "./Icon";

export interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
  className?: string;
  strokeWidth?: number;
}

// Registry of All Core App Icons used across Nestora
export const Icons = {
  // Brand & Custom
  Logo: NestoraLogo,
  Badminton: BadmintonIcon,
  Swimming: SwimmingIcon,
  Pool: SwimmingIcon,

  // Navigation & Role Dashboard Icons
  Overview: LucideIcons.Sparkles,
  Dashboard: LucideIcons.LayoutDashboard,
  ServiceRequests: LucideIcons.Wrench,
  Wrench: LucideIcons.Wrench,
  BoardTasks: LucideIcons.Briefcase,
  Briefcase: LucideIcons.Briefcase,
  Meetings: LucideIcons.Calendar,
  Calendar: LucideIcons.Calendar,
  Committees: LucideIcons.Users,
  Users: LucideIcons.Users,
  User: LucideIcons.User,
  UserCheck: LucideIcons.UserCheck,
  UserPlus: LucideIcons.UserPlus,
  Election: LucideIcons.CheckSquare,
  CheckSquare: LucideIcons.CheckSquare,
  Socials: LucideIcons.Megaphone,
  Megaphone: LucideIcons.Megaphone,
  Amenities: LucideIcons.Coffee,
  Coffee: LucideIcons.Coffee,
  Documents: LucideIcons.FileText,
  FileText: LucideIcons.FileText,
  File: LucideIcons.File,
  FileImage: LucideIcons.FileImage,
  Financials: LucideIcons.PieChart,
  PieChart: LucideIcons.PieChart,
  BarChart: LucideIcons.BarChart2,
  Budget: LucideIcons.Banknote,
  Bank: LucideIcons.Landmark,
  Building: LucideIcons.Building,
  Building2: LucideIcons.Building2,
  UnitDocument: LucideIcons.Home,
  Home: LucideIcons.Home,
  EmailActivity: LucideIcons.Mail,
  Mail: LucideIcons.Mail,
  Inspection: LucideIcons.ClipboardList,
  Security: LucideIcons.Shield,
  Shield: LucideIcons.Shield,
  ShieldCheck: LucideIcons.ShieldCheck,
  ShieldAlert: LucideIcons.ShieldAlert,
  Marketplace: LucideIcons.ShoppingBag,
  ShoppingBag: LucideIcons.ShoppingBag,
  Store: LucideIcons.Store,
  Wallet: LucideIcons.Wallet,

  // Action & Form Icons
  Plus: LucideIcons.Plus,
  Minus: LucideIcons.Minus,
  Edit: LucideIcons.Edit3,
  Edit2: LucideIcons.Edit2,
  Trash: LucideIcons.Trash2,
  Trash2: LucideIcons.Trash2,
  Search: LucideIcons.Search,
  Filter: LucideIcons.Filter,
  Check: LucideIcons.Check,
  CheckCircle: LucideIcons.CheckCircle2,
  CheckCircle2: LucideIcons.CheckCircle2,
  Close: LucideIcons.X,
  X: LucideIcons.X,
  XCircle: LucideIcons.XCircle,
  Menu: LucideIcons.Menu,
  ChevronDown: LucideIcons.ChevronDown,
  ChevronRight: LucideIcons.ChevronRight,
  ChevronLeft: LucideIcons.ChevronLeft,
  ChevronUp: LucideIcons.ChevronUp,
  ArrowRight: LucideIcons.ArrowRight,
  ArrowLeft: LucideIcons.ArrowLeft,
  ArrowDownLeft: LucideIcons.ArrowDownLeft,
  Upload: LucideIcons.Upload,
  UploadCloud: LucideIcons.UploadCloud,
  Download: LucideIcons.Download,
  Paperclip: LucideIcons.Paperclip,
  Send: LucideIcons.Send,
  Share: LucideIcons.Share2,
  Pin: LucideIcons.Pin,
  Clock: LucideIcons.Clock,
  Lock: LucideIcons.Lock,
  Key: LucideIcons.Key,
  KeyRound: LucideIcons.KeyRound,
  Eye: LucideIcons.Eye,
  EyeOff: LucideIcons.EyeOff,
  Bell: LucideIcons.Bell,
  Heart: LucideIcons.Heart,
  Star: LucideIcons.Star,
  Sparkles: LucideIcons.Sparkles,
  MessageSquare: LucideIcons.MessageSquare,
  MessageCircle: LucideIcons.MessageCircle,
  MapPin: LucideIcons.MapPin,
  Phone: LucideIcons.Phone,
  QrCode: LucideIcons.QrCode,
  CreditCard: LucideIcons.CreditCard,
  IndianRupee: LucideIcons.IndianRupee,
  DollarSign: LucideIcons.DollarSign,
  Car: LucideIcons.Car,
  Package: LucideIcons.Package,
  PackageCheck: LucideIcons.PackageCheck,
  Tag: LucideIcons.Tag,
  Dumbbell: LucideIcons.Dumbbell,
  Utensils: LucideIcons.Utensils,
  Camera: LucideIcons.Camera,
  Video: LucideIcons.Video,
  Smile: LucideIcons.Smile,
  LogOut: LucideIcons.LogOut,
  LogIn: LucideIcons.LogIn,
  MoreHorizontal: LucideIcons.MoreHorizontal,
  Refresh: LucideIcons.RefreshCw,
  AlertCircle: LucideIcons.AlertCircle,
  AlertTriangle: LucideIcons.AlertTriangle,
  Info: LucideIcons.Info,
  CircleHelp: LucideIcons.CircleHelp,
  Copy: LucideIcons.Copy,
  Save: LucideIcons.Save,
  Settings: LucideIcons.Settings,
  Layers: LucideIcons.Layers,
  LayoutGrid: LucideIcons.LayoutGrid,
  StopCircle: LucideIcons.StopCircle,
  GripVertical: LucideIcons.GripVertical,
  GraduationCap: LucideIcons.GraduationCap,
  Dog: LucideIcons.Dog,
  Activity: LucideIcons.Activity,
  BadgeAlert: LucideIcons.BadgeAlert,
  Box: LucideIcons.Box,
  History: LucideIcons.History,
  List: LucideIcons.List,
};

export type IconName = keyof typeof Icons;

// Direct re-exports
export { Icon, BadmintonIcon, SwimmingIcon, NestoraLogo };
export default Icons;
